from typing import Any, Optional

class Item:
    value: int
    slug: str
    display: str
    def __init__(self, value: int, slug: str, display: Optional[str] = None) -> None: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: Item) -> bool: ...
    def __le__(self, other: Item) -> bool: ...
    def __gt__(self, other: Item) -> bool: ...
    def __ge__(self, other: Item) -> bool: ...
